version: '3.5'
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus-compose
    restart: no
    ports:
      - "9090:9090"
    volumes:
      - "/Users/chenpeng/software/dockercompose/prometheus/config/prometheus.yml:/etc/prometheus/prometheus.yml"
  grafana:
    image: grafana/grafana:latest
    container_name: grafana-compose
    restart: no
    ports:
      - "3000:3000"
