# deploy-mydemo.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-golang-app-demo
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-golang-app-demo
  template:
    metadata:
      labels:
        app: my-golang-app-demo
    spec:
      containers:
        - image: pengdylan7/my-golang-app:latest
          name: my-golang-app-demo
          ports:
            - name: port1
              containerPort: 8991
              protocol: TCP
            - name: port2
              containerPort: 8992
              protocol: TCP